server:
  port: 10011
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.8.159.44:3306/funsport?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: UserProvider
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.8.159.44:8761/eureka/
